### ISSUE TITLE
If someone needs php8 version.

### ISSUE THREAD

**Issue by alxbndrs** [AzimoLabs/apple-sign-in-php-sdk#10]
I updated code to PHP8. If you need php8 right now, you can temporary use version from my repo. I didn't make PR because I dramatically changed the root service.

https://github.com/alxbndrs/apple-sign-in-php-sdk

[COMMIT] https://github.com/alxbndrs/apple-sign-in-php-sdk/commit/c3166ce14a629bc3a80feeb4cda6b921fd80bd2d

**Comment by hywak** [comment]
Hey @alxbndrs,

That's awesome, thank you. I will take a closer look at your fork and apply changes in the main repo to make it works with PHP 8.

**Comment by bbeckford** [comment]
Hey @hywak, any plans to merge this one? Thanks! :)

**Comment by hywak** [comment]
@bbeckford Updating the library to PHP 8 is the top priority on my to-do list but I can't find time to do that. Feel free to open a pull request with changes. I'd be glad to review and merge it.

**Comment by hywak** [comment]
@bbeckford PHP 8 support is available since tag `2.0.0`

https://github.com/AzimoLabs/apple-sign-in-php-sdk/releases/tag/2.0.0
