### ISSUE TITLE
Implicit conversion of keys from strings is deprecated.

### ISSUE THREAD

**Issue by tsaiyihua** [AzimoLabs/apple-sign-in-php-sdk#2]
Hi, 

I got the error while getting access token from apple.
`Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes.`

I find it cause by the problem from lcobucci/jwt 3.4.* , so I use "lcobucci/jwt": "3.3.*" in my project and it work perfectly.

The latest version of lcobucci/jwt is 4.1.x, but not released, I hasn't test it too.

**Comment by hywak** [comment]
Hey @tsaiyihua,
Thanks for creating an issue.

Could you please provide full stack trace?

**Comment by tsaiyihua** [comment]
No, It just give me the error message.

In the code, it use trigger_errors with E_USER_DEPRECATED

lcobucci/jwt  3.4.2

file vendor/lcobucci/jwt/src/Signer/BaseSigner.php
line 49 - 63
```
    /**
     * @param Key|string $key
     *
     * @return Key
     */
    private function getKey($key)
    {
        if (is_string($key)) {
            trigger_error('Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes.', E_USER_DEPRECATED);

            $key = new Key($key);
        }

        return $key;
    }
```

**Comment by hywak** [comment]
I have done a quick fix for that setting `lcobucci/jwt` an explicit version `3.3.3.`. Proper fix requires updating `lcobucci/jwt` version to 4.x.

Please tell me if that works for you, I will close the issue then.
https://github.com/AzimoLabs/apple-sign-in-php-sdk/releases/tag/1.2.0

**Comment by tsaiyihua** [comment]
> I have done a quick fix for that setting `lcobucci/jwt` an explicit version `3.3.3.`. Proper fix requires updating `lcobucci/jwt` version to 4.x.
> 
> Please tell me if that works for you, I will close the issue then.
> https://github.com/AzimoLabs/apple-sign-in-php-sdk/releases/tag/1.2.0

Yes, it works for me at 1.2.0, thanks a lot :)

**Comment by hywak** [comment]
You are welcome, thanks for raising the issue.
