### ISSUE TITLE
Azimo\Apple\Api\Exception\UnsupportedCryptographicAlgorithmException Cryptographic algorithm `fh6Bs8C` is not supported. Supported algorithms: `86D88Kf,eXaunmL,YuyXoY,W6WcOKB`

### ISSUE THREAD

**Issue by olucvolkan** [AzimoLabs/apple-sign-in-php-sdk#28]
We are using 1.1.2 version. What is the solution? Do you have idea?
Azimo\Apple\Api\Exception\UnsupportedCryptographicAlgorithmException
Cryptographic algorithm `fh6Bs8C` is not supported. Supported algorithms: `86D88Kf,eXaunmL,YuyXoY,W6WcOKB`

**Comment by ThomasCooks** [comment]
This may help: #29

**Comment by hywak** [comment]
Hey @olucvolkan,

Sorry for the inconvenience. The fix posted by @ThomasCooks was released to version 2.x.x but I haven't time to back-port changes. Thank you @ThomasCooks for the MR.

@olucvolkan please use this tag https://github.com/AzimoLabs/apple-sign-in-php-sdk/releases/tag/1.1.4 and let me know if it has fixed your problem.

**Comment by olucvolkan** [comment]
Thank you for support @ThomasCooks @hywak  It works!
