### ISSUE TITLE
Way to handle multiple audience?

### ISSUE THREAD

**Issue by fd6130** [AzimoLabs/apple-sign-in-php-sdk#31]
Hi, if I have two app (dev and prod) and they have different audience how can I handle that in this library?

At first I have tried this approach but it doesn't work since this library will throw exception when audience doesn't match.

```php
new Auth\Jwt\JwtValidator(
                new \Lcobucci\JWT\Validation\Validator(),
                [
                    new \Lcobucci\JWT\Validation\Constraint\IssuedBy('https://appleid.apple.com'),
                    new \Lcobucci\JWT\Validation\Constraint\PermittedFor('com.c.azimo.stage'),
                   new \Lcobucci\JWT\Validation\Constraint\PermittedFor('com.c.azimo.stage2'),
                ]
      ),
```

**Comment by fd6130** [comment]
> Hey @fd6130,
> 
> Thank for your question.
> 
> You will have to create 2 different instances of `JwtVelidator` and inject the proper instance depending on a profile.
> 
> ```
> $prodJwtValidator = new Auth\Jwt\JwtValidator(
>                 new \Lcobucci\JWT\Validation\Validator(),
>                 [
>                     new \Lcobucci\JWT\Validation\Constraint\IssuedBy('https://appleid.apple.com'),
>                     new \Lcobucci\JWT\Validation\Constraint\PermittedFor('com.c.azimo.stage')
>                 ]
>       ),
> $stageJwtValidator = new Auth\Jwt\JwtValidator(
>                 new \Lcobucci\JWT\Validation\Validator(),
>                 [
>                     new \Lcobucci\JWT\Validation\Constraint\IssuedBy('https://appleid.apple.com'),
>                    new \Lcobucci\JWT\Validation\Constraint\PermittedFor('com.c.azimo.stage2')
>                 ]
>       ),
> ```

Oh my, so I have to create two `AppleJwtFetchingService` instance for this case? Might quite inconvenient for app that have one login api only.

Thanks for the help, I think i will try to think about a better solution and if posible i will purpose a PR later.

**Comment by hywak** [comment]
I think it's kinda industry standard to have the prod and stage environments separated.

I'm happy to review the PR.

**Comment by fd6130** [comment]
> I think it's kinda industry standard to have the prod and stage environments separated.

Oh right, you got a point. I will think about it first, thanks!
