### ISSUE TITLE
Add support for lcobucci/jwt ^5.0

### ISSUE THREAD

**Issue by ovidiuenache** [AzimoLabs/apple-sign-in-php-sdk#35]
Hello! The _lcobucci/jwt_ package has a new major version that is currently not supported (see https://packagist.org/packages/lcobucci/jwt). Can we please release a new version that adds support for it? Thank you!

**Comment by hywak** [comment]
Hey @ovidiuenache,

Thank you for your issue report! Sure we can, feel free to submit a Pull request with the changes. It shouldn't be so difficult to add support to a new version, however, it's a major change so it might not be backward compatible.

**Comment by ovidiuenache** [comment]
@hywak I prepared a branch with the update but I am unable to push. I believe there is a permission issue. Can you please grant me access so I can push and create the PR?

**Comment by ovidiuenache** [comment]
@hywak https://github.com/AzimoLabs/apple-sign-in-php-sdk/pull/36

**Comment by hywak** [comment]
The PR you created was merged and tagged with [3.0.0](https://github.com/AzimoLabs/apple-sign-in-php-sdk/releases/tag/3.0.0)

Thank you @ovidiuenache for your contribution <3
