### ISSUE TITLE
Cryptographic algorithm `fh6Bs8C` is not supported.

### ISSUE THREAD

**Issue by sadakov** [AzimoLabs/apple-sign-in-php-sdk#38]
Can you add new cryptographic algorithm fh6Bs8C?

We use v3 version.

**Comment by hywak** [comment]
There is no algorithm validation anymore in the newest versions. The algorithms are fetched from the API. Maybe your API is misconfigured and the `fh6Bs8C` algorithm is disabled? 🤔 

1) https://github.com/AzimoLabs/apple-sign-in-php-sdk/blob/b2e5655ccd09b545a2e5f84113a068adc48b4607/src/Api/AppleApiClient.php#L25
2) https://github.com/AzimoLabs/apple-sign-in-php-sdk/blob/b2e5655ccd09b545a2e5f84113a068adc48b4607/src/Api/Factory/ResponseFactory.php#L34

**Comment by hywak** [comment]
@sadakov Did you manage to solve your problem?

**Comment by sadakov** [comment]
There were no more errors, but before that we had the latest version installed.
I'll close the issue for now, but if something happens I'll re-open it.
