### ISSUE TITLE
Correction to Installation

### ISSUE THREAD

**Issue by konradstrek** [AzimoLabs/apple-sign-in-php-sdk#5]
Hi! Should be ``composer require azimolabs/apple-sign-in-php-sdk:1.2.0`` in ``README.md``

**Comment by hywak** [comment]
Hey @konradstrek,
Thanks for pointing it out. I've updated the readme in cf994845661abdd7dfbe89c410491b8f0c2f7a45.

Don't hesitate to open a pull request with a change in the future.
