### ISSUE TITLE
Cryptographic algorithm `YuyXoY` is not supported. Supported algorithms: `86D88Kf,eXaunmL`

### ISSUE THREAD

**Issue by AlexNovicov** [AzimoLabs/apple-sign-in-php-sdk#7]
Hi!

Can you add new cryptographic algorithm `YuyXoY`?

**Comment by hywak** [comment]
Hey @AlexNovicov,

Thanks for raising the issue. It was a quite crucial issue. I've fixed it immediately in version `1.3.0`.

See https://github.com/AzimoLabs/apple-sign-in-php-sdk/releases/tag/1.3.0

**Comment by AlexNovicov** [comment]
Thank's

**Comment by hywak** [comment]
Is it working for you? Can I close the issue?

**Comment by AlexNovicov** [comment]
It working, thank's
